using Godot;
using System.IO;

public partial class Console : Node
{
    CanvasLayer _console;

    public override void _Ready()
    {
        _console = GetTree().Root.GetNode<CanvasLayer>("Console");
    }

    /// <summary>
    /// This is a hack until we can fix the code generated by GodotPluginsInitializerGenerator to specify it means System.Console not this Console
    /// https://github.com/godotengine/godot/pull/72434
    /// </summary>
    public static TextWriter Error => System.Console.Error;

    public CommandBuilder AddCommand(string name, GodotObject target, string targetMethodName)
    {
        GodotObject consoleCommand = _console.Call("add_command", name, target, targetMethodName).Obj as GodotObject;
        return new CommandBuilder(consoleCommand);
    }
}
